---
title: An R Markdown document converted from "STEP_6_AIM_1_Tempus_Test.ipynb"
output: html_document
---

Changes:

* Subsetting to genes that are present in all data sources.. array, RNA-seq, and TEMPUS. 10363 genes.
* Subsetting the JIVE gene signatures to those present genes.

Questions: Are there missing genes, in array, that are present in RNA-seq, that would be better to have for TEMPUS?



```{r}
#devtools::install_github("gibbsdavidl/robencla", force = F)
```

```{r}
library(tidyverse)
library(robencla)
library(survival)
library(survminer)
```


```{r}

# Take the data set, and filter out pair genes that are not present.

clean_genepairs_list <- function(genepairs, dat_x) {
  genepairs_clean <- list()
  i <- 1
  for (pi in names(genepairs)) {
    genes <- genepairs[[pi]]
    missing_genes <- unique( genes [! genes %in% colnames(dat_x)] )
    print(paste0(pi, '  ', missing_genes))
    newpairlist <- c()
    for (j in seq.int(from=1,to=length(genes), by=2)) {
      if ( (genes[j] %in% missing_genes) | (genes[j+1] %in% missing_genes) ) {
        # then don't add them!
        print(paste0("removing from pair list:  ", genes[j], ' ', genes[j+1]))
      } else {
        newpairlist <- c(newpairlist, genes[j], genes[j+1])
      }
    }
    genepairs_clean[[pi]] <- newpairlist
  }
  return(genepairs_clean)
}

# pairlist is a list of vectors (paired terms)
# n is the number of pairs for each entry desired

shorter_plist <- function(pairlist, n) {
  newlist <- list()
  for (ni in names(pairlist)) {
    newlist[[ni]] <- pairlist[[ni]][1:(2*n)]
  }
  return(newlist)  
}



```


```{r}
# Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
# arr_f <- read_csv('../data/jive_training_array_data_F.csv.gz')
# tmp_f <- read_csv('../data/Tempus_Females_unstranded.csv.gz')
# 
# load('../results/results_no_array_min/females_genepairs.rda')
# gset1 <- genepairs
# 
# load('../results/females_genepairs_val.rda')
# gset2 <- genepairs
# 
# load('../results/females_genepairs_rna.rda')
# gset3 <- genepairs

load('../data/F_processed_data.rda')
load('../data/f_genepairs.rda')

tempus.clin <- read.csv('../data/TEMPUS_Clinical_Data.csv.gz')
```

```{r}

gset <- fgenepairs$rna

gpairs <- shorter_plist(gset, 10)  

lapply(gpairs, function(x) x[! (x %in% colnames(dat_f ))] )
lapply(gpairs, function(x) x[! (x %in% colnames(tmp_f))] ) # missing "FABP5"  "CD24"   "LGALS3"

# clean the pairs
genepairs_cl <- clean_genepairs_list(gpairs, tmp_f)  # only one with missing genes

gs1 <- c(unlist(unique(genepairs_cl)), "Barcode", "ClusterLabel")
gs2 <- c(unlist(unique(genepairs_cl)), "Barcode", "Survival", "Censored")

colnames(tmp_f)[19939:19940] <- c('Censored','Survival')
colnames(tmp_f)[1] <- 'Barcode'

dat_f2 <- dat_f[,gs1]
tmp_f2 <- tmp_f[,gs2]

# what if ...
dat_f2$ClusterLabel2 <- ifelse(dat_f$ClusterLabel == 'cluster3', yes = 'C3', no='notC3')
c3_pairs <- list()
c3_pairs[['C3']] <- genepairs_cl$cluster3
c3_pairs[['notC3']] <- c(genepairs_cl$cluster1, genepairs_cl$cluster2, genepairs_cl$cluster4, genepairs_cl$cluster5)


# xgboost parameters to pass to each sub-classifier in the ensembles
# xgboost parameters to pass to each sub-classifier in the ensembles
params1 <- list(max_depth=6,   # "height" of the tree, 6 is actually default. I think about 12 seems better.  (xgboost parameter)
               eta=0.45,        # this is the learning rate. smaller values slow it down, more  conservative   (xgboost parameter)
               nrounds=24,     # number of rounds of training, lower numbers less overfitting (potentially)  (xgboost parameter)
               early_stopping_rounds=2,
               nthreads=8,     # parallel threads
               gamma=1.2,      # Minimum loss req'd to again partition a leaf node. higher number ~ more conservative (xgboost)
               lambda=2.5,     # L2 regularization term on weights, higher number ~ more conservative (xgboost parameter)
               alpha=1.2,      # L1 regularization term on weights. higher number ~ more conservative (xgboost parameter)
               verbose=0,
               train_perc=0.8,
               combine_function='median',
               size=11
)


mod_f <- robencla::Robencla$new('f_model')

mod_f$train(data_frame=dat_f,
            label_name='ClusterLabel', #'ClusterLabel2',
            sample_id = 'Barcode',
            drop_list = c(),
            data_mode=c('pairs'),    # pairs, allpairs, sigpairs, quartiles, tertiles, binarize, ranks, original #
            signatures=NULL,         # 
            pair_list=genepairs_cl,  # c3_pairs   # subset to these genes.
            params=params1
            )


# run the model
mod_f$predict(data_frame = tmp_f2, 
              sample_id = 'Barcode',
              drop_list = c('Survival', 'Censored'))


# check the predictions
table(mod_f$results()$BestCall)
#cluster1 cluster2 cluster3 cluster4 cluster5 
#      43        3       10        5       25 

head(mod_f$results())

# get the results table
resdf <- mod_f$results()
# add in the survival and censored
resdf$Survival <- mod_f$test_data$Survival
resdf$Censored <- mod_f$test_data$Censored

# convert scores to numerics
resdf$cluster1 <- unlist(resdf$cluster1)
resdf$cluster2 <- unlist(resdf$cluster2)
resdf$cluster3 <- unlist(resdf$cluster3)
resdf$cluster4 <- unlist(resdf$cluster4)
resdf$cluster5 <- unlist(resdf$cluster5)


r2 <- inner_join(resdf, tempus.clin, join_by(SampleIDs==Study.ID) )
write.csv(r2, file = 'results/F_Tempus_results.csv')

resdf$CensoredCode <- ifelse(resdf$Censored == 'alive', yes=1, no=2)

modfit <- survfit(Surv(Survival, CensoredCode)~BestCalls,data=resdf)
ggsurvplot(modfit, pval = T, xlim=c(0,1700))


#surp <- ggsurvplot(modfit, pval = T, xlim=c(0,1700) )
#surp
#ggsave("../figures/survplot_tempus_refined_features_F.pdf", surp$plot, height = 5, width = 10)

# scores for the samples called cluster3
#boxplot(as.numeric(resdf$cluster3)~as.factor(resdf$BestCalls))


#boxplot(as.numeric(resdf$C3)~as.factor(resdf$BestCalls))

```




MALES




```{r}

load('../data/M_processed_data.rda')
load('../data/m_genepairs.rda')


tempus.clin <- read.csv('../data/TEMPUS_Clinical_Data.csv.gz')
```

```{r}

gset <- m_genepairs$rna

gpairs <- shorter_plist(gset, 24)  

lapply(gpairs, function(x) x[! (x %in% colnames(dat_m ))] )
lapply(gpairs, function(x) x[! (x %in% colnames(tmp_m))] ) # missing "FABP5"  "CD24"   "LGALS3"

# clean the pairs
genepairs_cl <- clean_genepairs_list(gpairs, tmp_m)  # only one with missing genes

gs1 <- c(unlist(unique(genepairs_cl)), "Barcode", "ClusterLabel")
gs2 <- c(unlist(unique(genepairs_cl)), "Barcode", "Survival", "Censored")

dat_m2 <- dat_m[,gs1]
tmp_m2 <- tmp_m[,gs2]

# what if ...
dat_m2$ClusterLabel2 <- ifelse(dat_m$ClusterLabel == 'cluster3', yes = 'C3', no='notC3')
c3_pairs <- list()
c3_pairs[['C3']] <- genepairs_cl$cluster3
c3_pairs[['notC3']] <- c(genepairs_cl$cluster1, genepairs_cl$cluster2, genepairs_cl$cluster4, genepairs_cl$cluster5)


# xgboost parameters to pass to each sub-classifier in the ensembles
# xgboost parameters to pass to each sub-classifier in the ensembles
params1 <- list(max_depth=6,   # "height" of the tree, 6 is actually default. I think about 12 seems better.  (xgboost parameter)
               eta=0.3,        # this is the learning rate. smaller values slow it down, more  conservative   (xgboost parameter)
               nrounds=24,     # number of rounds of training, lower numbers less overfitting (potentially)  (xgboost parameter)
               early_stopping_rounds=2,
               nthreads=8,     # parallel threads
               gamma=0.2,      # Minimum loss req'd to again partition a leaf node. higher number ~ more conservative (xgboost)
               lambda=2.5,     # L2 regularization term on weights, higher number ~ more conservative (xgboost parameter)
               alpha=0.25,      # L1 regularization term on weights. higher number ~ more conservative (xgboost parameter)
               verbose=0,
               train_perc=0.8,
               combine_function='median',
               size=11
)


mod_m <- robencla::Robencla$new('m_model')

mod_m$train(data_frame=dat_m,
            label_name='ClusterLabel', #'ClusterLabel2',
            sample_id = 'Barcode',
            drop_list = c('Sex'),
            data_mode=c('pairs'),    # pairs, allpairs, sigpairs, quartiles, tertiles, binarize, ranks, original #
            signatures=NULL,         # 
            pair_list=genepairs_cl,  # c3_pairs   # subset to these genes.
            params=params1
            )


# run the model
mod_m$predict(data_frame = tmp_m2, 
              sample_id = 'Barcode',
              drop_list = c('Survival', 'Censored'))


# check the predictions
table(mod_m$results()$BestCall)
#cluster1 cluster2 cluster3 cluster5 
#      51       70       13       16 

# set 1 - 24 pairs
#cluster1 cluster2 cluster3 cluster4 cluster5 
#       2       83        3       21       41 

head(mod_m$results())

# get the results table
resdf <- mod_m$results()
# add in the survival and censored
resdf$Survival <- mod_m$test_data$Survival
resdf$Censored <- mod_m$test_data$Censored

# convert scores to numerics
resdf$cluster1 <- unlist(resdf$cluster1)
resdf$cluster2 <- unlist(resdf$cluster2)
resdf$cluster3 <- unlist(resdf$cluster3)
resdf$cluster4 <- unlist(resdf$cluster4)
resdf$cluster5 <- unlist(resdf$cluster5)

resdf$CensoredCode <- ifelse(resdf$Censored == 0, yes=1, no=2)

modfit <- survfit(Surv(Survival, CensoredCode)~BestCalls,data=resdf)
ggsurvplot(modfit, pval = T, xlim=c(0,1700))


r2 <- inner_join(resdf, tempus.clin, join_by(SampleIDs==Study.ID) )
write.csv(r2, file = 'results/M_Tempus_results.csv')

surp <- ggsurvplot(modfit, pval = T, xlim=c(0,1700) )
#surp
ggsave("../figures/survplot_tempus_refined_features_M.pdf", surp$plot, height = 8, width = 8)

# scores for the samples called cluster3
#boxplot(as.numeric(resdf$cluster3)~as.factor(resdf$BestCalls))


#boxplot(as.numeric(resdf$C3)~as.factor(resdf$BestCalls))

```

