---
title: An R Markdown document converted from "STEP_5_AIM_1_RNASeq_Test.ipynb"
output: html_document
---


```{r}
#devtools::install_github("gibbsdavidl/robencla", force = F)
```

```{r}
library(tidyverse)
library(robencla)
library(pheatmap)
library(readr)
```


```{r}




# Take the data set, and filter out pair genes that are not present.

clean_genepairs_list <- function(genepairs, dat_x) {
  genepairs_clean <- list()
  i <- 1
  for (pi in names(genepairs)) {
    genes <- genepairs[[pi]]
    missing_genes <- unique( genes [! genes %in% colnames(dat_x)] )
    print(paste0(pi, '  ', missing_genes))
    newpairlist <- c()
    for (j in seq.int(from=1,to=length(genes), by=2)) {
      if ( (genes[j] %in% missing_genes) | (genes[j+1] %in% missing_genes) ) {
        # then don't add them!
        print(paste0("removing from pair list:  ", genes[j], ' ', genes[j+1]))
      } else {
        newpairlist <- c(newpairlist, genes[j], genes[j+1])
      }
    }
    genepairs_clean[[pi]] <- newpairlist
  }
  return(genepairs_clean)
}

# pairlist is a list of vectors (paired terms)
# n is the number of pairs for each entry desired

shorter_plist <- function(pairlist, n) {
  newlist <- list()
  for (ni in names(pairlist)) {
    newlist[[ni]] <- pairlist[[ni]][1:(2*n)]
  }
  return(newlist)  
}


```

```{r}


library(readr)
library(robencla)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

dat_f <- read_csv('../data/jive_training_array_data_F.csv.gz')
dat_f <- dat_f[,-1] # remove the first column

val_f <- read_csv('../data/Females_RNASeq_Data_unstranded.csv.gz')

load("../results/females_genepairs.rda")

```
```{r}

# checking the correlation between platforms

gene <- genepairs$cluster3[1]

barcodes <- str_sub(dat_f$Barcode, 1, 12)
d1 <- data.frame(Barcode=barcodes, ArrayGene=dat_f[,gene], Cluster=dat_f$ClusterLabel)
colnames(d1)[2] <- 'ArrayGene'
rownames(d1) <-barcodes

r1 <- data.frame(Barcode=val_f$sample, RNASeqGene=val_f[,gene])
colnames(r1)[2] <- 'RNASeqGene'
rownames(r1) <- r1$Barcode

x1 <- inner_join(d1,r1)

qplot(x=ArrayGene, y=RNASeqGene, color=Cluster, data=x1)

print( cor(x1$ArrayGene, x1$RNASeqGene) )
```



```{r}

gpairs <- shorter_plist(genepairs, 5)

lapply(gpairs, function(x) x[! (x %in% colnames(dat_f ))] )
lapply(gpairs, function(x) x[! (x %in% colnames(val_f ))] ) # missing "FABP5"  "CD24"   "LGALS3"

# clean the pairs
genepairs_cl <- clean_genepairs_list(gpairs, dat_f)  # only one with missing genes
genepairs_cl <- clean_genepairs_list(genepairs_cl, val_f)  # only one with missing genes

gs <- c(unlist(unique(genepairs_cl)), "SampleID", "Sex", "Survival", "Censored")

# xgboost parameters to pass to each sub-classifier in the ensembles
params <- list(max_depth=12,   # "height" of the tree, 6 is actually default. I think about 12 seems better.  (xgboost parameter)
               eta=0.35,        # this is the learning rate. smaller values slow it down, more  conservative   (xgboost parameter)
               nrounds=32,     # number of rounds of training, lower numbers less overfitting (potentially)  (xgboost parameter)
               early_stopping_rounds=2,
               nthreads=8,     # parallel threads
               gamma=1.0,      # Minimum loss req'd to again partition a leaf node. higher number ~ more conservative (xgboost)
               lambda=2.5,     # L2 regularization term on weights, higher number ~ more conservative (xgboost parameter)
               alpha=1.0,      # L1 regularization term on weights. higher number ~ more conservative (xgboost parameter)
               verbose=0,
               train_perc=0.8,
               combine_function='median',
               size=11
)


mod_f <- robencla::Robencla$new('f_model')


mod_f$train(data_frame=dat_f,
            label_name='ClusterLabel',
            sample_id = 'Barcode',
            drop_list = c('Sex'),
            data_mode=c('pairs'), # pairs, allpairs, sigpairs, quartiles, tertiles, binarize, ranks, original #
            signatures=NULL,
            pair_list=genepairs_cl,  # subset to these genes.
            params=params
            )

# run the model
mod_f$predict(data_frame = val_f, 
              sample_id = 'value',
              label_name = 'cluster_group')


table(True=mod_f$test_label, Call=mod_f$results()$BestCall)


```


```{r}
resdf <- mod_f$results()
resdf$cluster1 <- unlist(resdf$cluster1)
resdf$cluster2 <- unlist(resdf$cluster2)
resdf$cluster3 <- unlist(resdf$cluster3)
resdf$cluster4 <- unlist(resdf$cluster4)
resdf$cluster5 <- unlist(resdf$cluster5)
resdf

boxplot(resdf$cluster3 ~ resdf$BestCalls)

resdf$Label <- mod_f$test_label

```



```{r}
gpairs <- shorter_plist(genepairs, 24)

lapply(gpairs, function(x) x[! (x %in% colnames(dat_f ))] )
lapply(gpairs, function(x) x[! (x %in% colnames(val_f ))] ) # missing "FABP5"  "CD24"   "LGALS3"

# clean the pairs
genepairs_cl <- clean_genepairs_list(gpairs, dat_f)  # only one with missing genes
genepairs_cl <- clean_genepairs_list(genepairs_cl, val_f)  # only one with missing genes


# results list
resl <- list()
print('starting')

dat_f$Barcode2 <- sapply(dat_f$Barcode, function(a) str_sub(a, start=1, end=12))

# for a number of iterations, could be more
for (i in 1:200) {

  idx <- sample(1:nrow(val_f),size=5,replace = F)
  sampleidx <- val_f$sample[idx]

  dfa3 <- dat_f[!(dat_f$Barcode2 %in% sampleidx), ]
  dfb3 <- val_f[c(idx), ]

  # our classifier object named Anne.
  anne <- Robencla$new("Anne")

  # xgboost parameters to pass to each sub-classifier in the ensembles
  params <- list(max_depth=12,   # "height" of the tree, 6 is actually default. I think about 12 seems better.  (xgboost parameter)
                 eta=0.35,        # this is the learning rate. smaller values slow it down, more  conservative   (xgboost parameter)
                 nrounds=24,     # number of rounds of training, lower numbers less overfitting (potentially)  (xgboost parameter)
                 early_stopping_rounds=2,
                 nthreads=8,     # parallel threads
                 gamma=0.25,      # Minimum loss req'd to again partition a leaf node. higher number ~ more conservative (xgboost)
                 lambda=2.5,     # L2 regularization term on weights, higher number ~ more conservative (xgboost parameter)
                 alpha=0.25,      # L1 regularization term on weights. higher number ~ more conservative (xgboost parameter)
                 verbose=0,
                 train_perc=0.8,
                 combine_function='median',
                 size=11
  )

  # First we use the training data
  anne$train(data_frame=dfa3,
            label_name='ClusterLabel',
            sample_id = 'Barcode',
            drop_list = c('Sex', 'Barcode2'),
            data_mode=c('pairs'), # pairs, allpairs, sigpairs, quartiles, tertiles, binarize, ranks, original #
            signatures=NULL,
            pair_list=genepairs_cl,  # subset to these genes.
            params=params
            )

  
  # now we apply the classifier to a test set.
  anne$predict(data_frame = dfb3,#[,colnames(dfa2)], #'data/Males_RNASeq_Data_v3.csv',
                label_name='cluster_group',
                sample_id = 'sample',
                verbose=0)

  #table(Pred=anne$results()$BestCall, True=anne$test_label)
  resl[[i]] <- data.frame(Round=i,   anne$results()$SampleIDs, Pred=anne$results()$BestCall, True=anne$test_label)
}

```


```{r}
resdf <- do.call("rbind", resl)

tabdf <- table(Pred=resdf$Pred, True=resdf$True)
```

```{r}
head(resdf)
```


```{r}
tabtbl <- as.data.frame(tabdf) %>% 
  pivot_wider(id_cols = Pred,names_from = True, values_from = Freq) %>% 
  select(-Pred) %>%
  scale(center = F) # Z-scores
rownames(tabtbl) <- rownames(tabdf)
pheatmap(tabtbl, cluster_rows = F, cluster_cols = F)

```




```{r}
xdf <- (resdf[resdf$True=='cluster3',2:4]) %>% arrange(anne.results...SampleIDs)
colnames(xdf)[1] <- 'SampleID'
ggplot(data=xdf, aes(x=as.factor(Pred), fill=as.factor(SampleID))) + geom_bar() + xlab("Predicted Cluster")
#ggsave(filename = 'results/female_rnaseq_test_pairs_quantiles_200_cluster1.png')
```


```{r}

write.table(as.data.frame(resdf), 'results/female_rnaseq_pairs_quantiles_round3_200.csv', sep=',', quote = F, row.names = F)

```


