---
title: An R Markdown document converted from "STEP_3_Feature_Selection_Processing_V3.ipynb"
output: html_document
---

```{r}
#devtools::install_github("gibbsdavidl/robencla", force = F)
```

```{r}
library(tidyverse)
```

```{r}

array_m <- read_csv('../data/jive_training_array_data_M.csv')

resdf_m <- read_csv('../results/feature_selection_table_male.csv')

(colnames(array_m))[12645:12647]
#[1] "Barcode"      "ClusterLabel" "Sex"  

table(resdf_m$cluster)

# drop the first column of row numbers
array_m <- array_m[,-1]


```

With the threshold held across clusters
cluster1 cluster2 cluster3 cluster4 cluster5 
       9        5      316      660    25568 


```{r}

# don't count the annotation columns at the end
array_ncol <- ncol(array_m)-3

# first get the min value for each gene in the array data
minExprVals <- apply(array_m[,1:array_ncol], 2, min, na.rm=T)

# first get the min value for each gene in the array data
medExprVals <- apply(array_m[,1:array_ncol], 2, median, na.rm=T)

# get gene IDs from the array
genesi <- colnames(array_m)[resdf_m$gene_i]
genesj <- colnames(array_m)[resdf_m$gene_j]

# get the medians and mins out
medi <- medExprVals[resdf_m$gene_i]
medj <- medExprVals[resdf_m$gene_j]
mini <- minExprVals[resdf_m$gene_i]
minj <- minExprVals[resdf_m$gene_j]


annotdf_m <- resdf_m
annotdf_m['gene_i_symbol'] <- genesi
annotdf_m['gene_j_symbol'] <- genesj
annotdf_m['gene_i_min'] <- mini
annotdf_m['gene_j_min'] <- minj
annotdf_m['gene_i_med'] <- medi
annotdf_m['gene_j_med'] <- medj

write.csv(annotdf_m, file = '../results/annotdf_m.csv')

```



```{r}

getpairs <- function(pairmat, cluster_c, thresh, topn) {

    #pairmat <- na.omit(pairmat)
  
    # remove unknown genes
    idx <- !str_detect(pairmat$gene_i_symbol,'unknown_')
    jdx <- !str_detect(pairmat$gene_j_symbol,'unknown_')
    pairmat <- pairmat[idx&jdx,]
  
    filtmat <- pairmat[(pairmat$cluster == cluster_c), ]
    # first filter the table by min expression value
    #filtmat <- pairmat[ (pairmat$gene_i_min > thresh) & 
    #                      (pairmat$gene_j_min > thresh) & 
    #                      (pairmat$cluster == cluster_c), ]
    
    #idx <- order(filtmat$dist_ij_cluster, decreasing = T)[1:topn]
    #jdx <- order(filtmat$dist_ij_cluster, decreasing = F)[1:topn]
    topn <- min(topn, nrow(filtmat))
    idx <- order(filtmat$prop_diff, decreasing = T)[1:topn]
    jdx <- order(filtmat$prop_diff, decreasing = F)[1:topn]

    upgenes <- c()
    for (i in idx) {
      upgenes <- c(upgenes, as.character(filtmat[i, 'gene_i_symbol']))
      upgenes <- c(upgenes, as.character(filtmat[i, 'gene_j_symbol']))
    }
    dngenes <- c()
    for (j in jdx) {
      dngenes <- c(dngenes, as.character(filtmat[j, 'gene_i_symbol']))
      dngenes <- c(dngenes, as.character(filtmat[j, 'gene_j_symbol']))
    }

    return( c(upgenes, dngenes) )    
}

genepairs <- list(
  'cluster1'=getpairs(annotdf_m, 'cluster1', 0, 10),
  'cluster2'=getpairs(annotdf_m, 'cluster2', 0, 10),
  'cluster3'=getpairs(annotdf_m, 'cluster3', 0, 10),
  'cluster4'=getpairs(annotdf_m, 'cluster4', 0, 10),
  'cluster5'=getpairs(annotdf_m, 'cluster5', 0, 10)
)

```

```{r}

# getting the gene pairs mapped correctly to symbols.

library(org.Hs.eg.db)

# fix the symbols with multi-maps
genepairs$cluster1[1]   <-"PLGLB2"
genepairs$cluster1[31]  <- "PLGLB2"

# for each cluster set, map to correct symbols
symbolpairs <- lapply(genepairs,
                      function(x) {
                        select(org.Hs.eg.db,
                               keys =  x,
                               columns=c("ENTREZID","SYMBOL"),
                               keytype="ALIAS")
                        
                      })

symbolpairs[["cluster1"]] <- symbolpairs[["cluster1"]][!symbolpairs$cluster1$ENTREZID %in% c(79947,23173),] 

symbolpairs[["cluster2"]]  # OK

symbolpairs[["cluster3"]] <- symbolpairs[["cluster3"]][!symbolpairs$cluster3$ENTREZID %in% c(92856),] # map IMP4 to SPPL2B

symbolpairs[["cluster4"]] <- symbolpairs[["cluster4"]][!symbolpairs$cluster4$ENTREZID %in% c(57147, 4669),] # map SCYL3 to CCL15
symbolpairs[["cluster4"]][symbolpairs$cluster4$ALIAS == 'KIAA0404','SYMBOL'] <- 'ATG2A'
symbolpairs[["cluster4"]][symbolpairs$cluster4$ALIAS == 'KIAA0664','SYMBOL'] <- 'CLUH'
symbolpairs[["cluster4"]][symbolpairs$cluster4$ALIAS == 'LOC63920','SYMBOL'] <- 'IRF8' 


symbolpairs[["cluster5"]] <- symbolpairs[["cluster5"]][!symbolpairs$cluster5$ENTREZID %in% c(770,100526739,51514,885,27165),] # map CA11 to GKN1, DTL to TNFSF13B, map CCK to RIPK2
symbolpairs[["cluster5"]][symbolpairs$cluster5$ALIAS == 'MGC39900','SYMBOL'] <- 'TMSB15B'
 

genepairs <- lapply(symbolpairs, function(x) x$SYMBOL)

```

```{r}

### Fix the gene names on the array now###

# first get the alias to symbol table 
fullmap <- rbind(symbolpairs$cluster1,symbolpairs$cluster2,
                 symbolpairs$cluster3, symbolpairs$cluster4,
                 symbolpairs$cluster5)
fullmap <- unique(fullmap)

# fix the multi-mapping colnames
which(str_detect(colnames(array_m), 'PLGLB2')) # 4099
colnames(array_m)[4099] <- "PLGLB2"

# for each alias, map in the correct symbol
for (i in 1:nrow(fullmap)){
  ai <- fullmap$ALIAS[i]
  si <- fullmap$SYMBOL[i]
  idx <- which(colnames(array_m) == ai) 
  print(paste0(ai, "  replaceing ", as.character(length(idx)), '  ', si))
  colnames(array_m)[idx] <- si
}

write_csv(array_m, file='../data/jive_training_array_data_M_v2.csv')
save(genepairs, file='../results/males_genepairs.rda')
```








# Now for the female samples # 






```{r}
### PULLING OUT SOME GENES

array_f  <- read_csv('../data/jive_training_array_data_F.csv')

resdf_f <- read_csv('../results/feature_selection_table_female.csv')

# drop the first column of row numbers
array_f <- array_f[,-1]

table(resdf_f$cluster)

tail(colnames(array_f))

```

```{r}

# don't count the annotation columns at the end
array_ncol <- ncol(array_f)-3

# first get the min value for each gene in the array data
minExprVals <- apply(array_f[,1:array_ncol], 2, min, na.rm=T)

# first get the min value for each gene in the array data
medExprVals <- apply(array_f[,1:array_ncol], 2, median, na.rm=T)

# get gene IDs from the array
genesi <- colnames(array_f)[resdf_f$gene_i]
genesj <- colnames(array_f)[resdf_f$gene_j]

# get the medians and mins out
medi <- medExprVals[resdf_f$gene_i]
medj <- medExprVals[resdf_f$gene_j]
mini <- minExprVals[resdf_f$gene_i]
minj <- minExprVals[resdf_f$gene_j]


annotdf_f <- resdf_f
annotdf_f['gene_i_symbol'] <- genesi
annotdf_f['gene_j_symbol'] <- genesj
annotdf_f['gene_i_min'] <- mini
annotdf_f['gene_j_min'] <- minj
annotdf_f['gene_i_med'] <- medi
annotdf_f['gene_j_med'] <- medj

write.csv(annotdf_f, file = '../results/annotdf_f.csv')
```




```{r}

# previously took prop_diff into account also
# resdf %>% dplyr::filter(cluster=='cluster1') %>% arrange( desc(abs(dist_ij_cluster))) %>% head(n=20)
# resdf %>% dplyr::filter(cluster=='cluster1') %>% arrange( desc(abs(prop_diff))) %>% head(n=20)

getpairs <- function(pairmat, cluster_c, thresh, topn) {

    #pairmat <- na.omit(pairmat)
  
    # remove unknown genes
    idx <- !str_detect(pairmat$gene_i_symbol,'unknown_')
    jdx <- !str_detect(pairmat$gene_j_symbol,'unknown_')
    pairmat <- pairmat[idx&jdx,]
  
    filtmat <- pairmat[(pairmat$cluster == cluster_c), ]
    # first filter the table by min expression value
    #filtmat <- pairmat[ (pairmat$gene_i_min > thresh) & 
    #                      (pairmat$gene_j_min > thresh) & 
    #                      (pairmat$cluster == cluster_c), ]
    
    #idx <- order(filtmat$dist_ij_cluster, decreasing = T)[1:topn]
    #jdx <- order(filtmat$dist_ij_cluster, decreasing = F)[1:topn]
    topn <- min(topn, nrow(filtmat))
    idx <- order(filtmat$prop_diff, decreasing = T)[1:topn]
    jdx <- order(filtmat$prop_diff, decreasing = F)[1:topn]
    
    upgenes <- c()
    for (i in idx) {
      upgenes <- c(upgenes, as.character(filtmat[i, 'gene_i_symbol']))
      upgenes <- c(upgenes, as.character(filtmat[i, 'gene_j_symbol']))
    }
    dngenes <- c()
    for (j in jdx) {
      dngenes <- c(dngenes, as.character(filtmat[j, 'gene_i_symbol']))
      dngenes <- c(dngenes, as.character(filtmat[j, 'gene_j_symbol']))
    }

    return( c(upgenes, dngenes) )    
}

genepairs <- list(
  'cluster1'=getpairs(annotdf_f, 'cluster1', 4.6, 10),
  'cluster2'=getpairs(annotdf_f, 'cluster2', 4.6, 10),
  'cluster3'=getpairs(annotdf_f, 'cluster3', 4.6, 10),
  'cluster4'=getpairs(annotdf_f, 'cluster4', 4.2, 10),
  'cluster5'=getpairs(annotdf_f, 'cluster5', 4.6, 10)
)

```


```{r}

save(genepairs, file='../results/females_genepairs.rda')

```

```{r}

# from the raw results pair table
#i <- 3654
#j <- 8660
#resdf_f[(resdf_f$gene_i == 3654) & (resdf_f$gene_j == 8660),]

#annotdf_f[(resdf_f$gene_i == 3654) & (resdf_f$gene_j == 8660),]

#       cluster  pair gene_i gene_j prop_this_cluster prop_not_cluster  dist_ij_cluster dist_ij_not_cluster prop_diff
#65921 cluster3 65921   3654   8660                 1                0 4.59547434916667   -91.0549842018055         1
```
