---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(robencla)
anne <- Robencla$new()
library(pheatmap)
```


```{r}
resdf <- read.csv('results/female_rnaseq_pairs_quantiles_round3_200.csv')
```


```{r}
anne$classification_metrics(these_calls = resdf$Pred, these_labels = resdf$True)
```

```{r}

resdf_rand <- resdf
resdf_rand$Pred <- sample(resdf_rand$Pred, size = nrow(resdf), replace = F)

anne$classification_metrics(these_calls = resdf_rand$Pred, these_labels = resdf_rand$True)

```





```{r}
resdf <- read.csv('results/female_tempus_pred_pairs_quantiles_1000_maj.csv')

resdf <- read.csv('results/male_tempus_pred_pairs_quantiles_200_maj.csv')


tabdf <- table(Majority=resdf$MajorityVote, BestCalls=resdf$BestCalls)

tabtbl <- as.data.frame(tabdf) %>% 
  pivot_wider(id_cols = Majority, names_from = BestCalls, values_from = Freq) %>% 
  select(-Majority) %>%
  scale(center = F) # Z-scores

rownames(tabtbl) <- colnames(tabtbl)

pheatmap(tabtbl, cluster_rows = F, cluster_cols = F)


```









