---
title: "feature_merge"
output: html_document
date: "2023-10-22"
---

Merging the feature search for each cluster.

```{r}
library(tidyverse)
library(readr)
```



```{r}

fc1 <- read_csv('results/run4/feature_pairs_females_cluster1.csv') # was thresh04
fc2 <- read_csv('results/run4/feature_pairs_females_cluster2.csv')
fc3 <- read_csv('results/run4/feature_pairs_females_cluster3.csv')
fc4 <- read_csv('results/run4/feature_pairs_females_cluster4.csv') # was thresh66
fc5 <- read_csv('results/run4/feature_pairs_females_cluster5.csv') # was thresh04


mc1 <- read_csv('results/run4/feature_pairs_males_cluster1.csv')
mc2 <- read_csv('results/run4/feature_pairs_males_cluster2.csv')
mc3 <- read_csv('results/run4/feature_pairs_males_cluster3.csv')
mc4 <- read_csv('results/run4/feature_pairs_males_cluster4.csv')
mc5 <- read_csv('results/run4/feature_pairs_males_cluster5.csv')

```


```{r}

resdf_f <- bind_rows(list(fc1, fc2, fc3, fc4, fc5))

resdf_m <- bind_rows(list(mc1, mc2, mc3, mc4, mc5))

```

```{r}

write_csv(resdf_f, file='../../results/feature_selection_table_female.csv')

write_csv(resdf_m, file='../../results/feature_selection_table_male.csv')


```


